### ISSUE TITLE
Spawning mobs as drops

### ISSUE THREAD

**Issue by Oharaicaine** [FatherToast/MobProperties#2]
no idea if i'm doing something wrong or it's a bug.

This does not work
  "drops": [
	{
		"function": "all",
		"count" 0.5,
		"functions": [
			{
			"function": "spawn",
			"id": "CaveSpider",
			"count": 1~3
			}
		]
	}
  ]

This does work but i can't set a chance to spawn
  "drops": [
	{
		"function": "spawn",
		"id": "CaveSpider",
		"count": 1~3
	}
  ]

**Comment by FatherToast** [comment]
Your `1~3` must be in quotes, like `"1~3"`.
